-- 0001_initial.sql
-- Core schema for Holistic Psychology Booking Platform (D1 / SQLite)
-- Principles:
-- - No PHI columns
-- - No client passwords
-- - Auditable writes via audit_logs

PRAGMA foreign_keys = ON;

BEGIN TRANSACTION;

-- Practitioners (practitioner-owned data)
CREATE TABLE IF NOT EXISTS practitioners (
  id TEXT PRIMARY KEY,                 -- UUID string generated by app
  display_name TEXT NOT NULL,           -- Public-facing name
  slug TEXT NOT NULL UNIQUE,            -- For SEO/public profile URLs (no PHI)
  public_bio TEXT DEFAULT NULL,         -- Must not contain PHI (content policy)
  timezone TEXT NOT NULL DEFAULT 'UTC', -- IANA tz e.g. "America/Los_Angeles"
  is_active INTEGER NOT NULL DEFAULT 1, -- 1=true, 0=false
  created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  updated_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now'))
);

-- Availability slots (public, bookable windows)
CREATE TABLE IF NOT EXISTS availability (
  id TEXT PRIMARY KEY,                 -- UUID
  practitioner_id TEXT NOT NULL,
  start_at TEXT NOT NULL,              -- ISO timestamp UTC
  end_at TEXT NOT NULL,                -- ISO timestamp UTC
  is_bookable INTEGER NOT NULL DEFAULT 1,
  created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  updated_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  FOREIGN KEY (practitioner_id) REFERENCES practitioners(id) ON DELETE CASCADE,
  CHECK (end_at > start_at)
);

-- Appointments (minimal client data for MVP; no sensitive notes)
CREATE TABLE IF NOT EXISTS appointments (
  id TEXT PRIMARY KEY,                 -- UUID
  practitioner_id TEXT NOT NULL,
  start_at TEXT NOT NULL,              -- ISO timestamp UTC
  end_at TEXT NOT NULL,                -- ISO timestamp UTC
  status TEXT NOT NULL DEFAULT 'booked',-- booked|canceled|completed
  client_email TEXT NOT NULL,          -- contact only (avoid notes/diagnosis)
  client_name TEXT DEFAULT NULL,       -- optional
  client_timezone TEXT DEFAULT NULL,   -- optional
  created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  updated_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  canceled_at TEXT DEFAULT NULL,
  FOREIGN KEY (practitioner_id) REFERENCES practitioners(id) ON DELETE CASCADE,
  CHECK (end_at > start_at)
);

-- Audit logs (log all writes; keep metadata minimal; do not store PHI)
CREATE TABLE IF NOT EXISTS audit_logs (
  id TEXT PRIMARY KEY,                 -- UUID
  actor_type TEXT NOT NULL,            -- 'practitioner'|'system'|'client'
  actor_id TEXT DEFAULT NULL,          -- practitioner id if available
  action TEXT NOT NULL,                -- e.g. 'create','update','delete','login'
  entity TEXT NOT NULL,                -- table or domain entity name
  entity_id TEXT DEFAULT NULL,         -- record id if applicable
  metadata_json TEXT DEFAULT NULL,     -- JSON string; must be safe/minimal (no PHI)
  request_id TEXT DEFAULT NULL,        -- trace id
  ip_hash TEXT DEFAULT NULL,           -- hash, not raw IP
  user_agent_hash TEXT DEFAULT NULL,   -- hash, not raw UA
  created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now'))
);

-- Indexes (performance)
CREATE INDEX IF NOT EXISTS idx_availability_practitioner_start
  ON availability(practitioner_id, start_at);

CREATE INDEX IF NOT EXISTS idx_availability_practitioner_end
  ON availability(practitioner_id, end_at);

CREATE INDEX IF NOT EXISTS idx_appointments_practitioner_start
  ON appointments(practitioner_id, start_at);

CREATE INDEX IF NOT EXISTS idx_appointments_status
  ON appointments(status);

CREATE INDEX IF NOT EXISTS idx_audit_created_at
  ON audit_logs(created_at);

CREATE INDEX IF NOT EXISTS idx_audit_entity
  ON audit_logs(entity, entity_id);

-- Prevent accidental duplicate exact-slot bookings (conflict prevention handled in API later)
CREATE UNIQUE INDEX IF NOT EXISTS uq_appointments_practitioner_exact_slot
  ON appointments(practitioner_id, start_at, end_at);

COMMIT;
